### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by illusi0nary** [arc-pune/arc-backend#23]
Create a user login that has a POST route for login on the "user" resource.

It should be checked if: 
* a user entered the correct username and password

Further you should take in consideration to return a valid signed JWT token for the frontend.

**Comment by illusi0nary** [comment]
Sure @akash-55  have fun with it :-)

**Comment by qwe123coder** [comment]
> hi, @illusi0nary assign this issue to me. I'd like to give it a try.

hey if your working on it could you give us updates as I am almost done with this and I could make a pr for this
